services:
  backstage:
    image: backstage
    env_file: 'backstage.env'
    ports:
      - '7007:7007'
    depends_on:
      - 'db'

  db:
    image: postgres:13
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
